// Written by Jon Sayer of Data Geeks Lab
// April 2022
// jon@datageekslab.com
//
// Test class for generateRandomString

@isTest
public with sharing class GenerateRandomString_TEST {
  @isTest
  static void test() {
    /*
    List<generateRandomString.FlowInputs> input = new List<generateRandomString.FlowInputs>();
    generateRandomString.FlowInputs i = new generateRandomString.FlowInputs();
    i.len = 32;
    input.add(i);
    generateRandomString.FlowInputs j = new generateRandomString.FlowInputs();
    j.len = 64;
    input.add(j);
    generateRandomString.FlowInputs k = new generateRandomString.FlowInputs();
    k.len = 420;
    input.add(k);

    List<generateRandomString.FlowOutputs> o = generateRandomString.generateRandomStringInvoke(
      input
    );

    system.assertEquals(32, o[0].out.length());
    system.assertEquals(64, o[1].out.length());
    system.assertEquals(420, o[2].out.length());
    */
  }
}
